// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSz_YVVvHMCjLcQoL4UC8L7-gV3Ti8iXk',
    appId: '1:254821797176:web:d37eb00cb7aab3581445cd',
    messagingSenderId: '254821797176',
    projectId: 'allobaby-a14cd',
    authDomain: 'allobaby-a14cd.firebaseapp.com',
    storageBucket: 'allobaby-a14cd.firebasestorage.app',
    measurementId: 'G-WY07KJH4PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBefh7kr8k1nKDaL5DeeXxM-WvAABGenEk',
    appId: '1:254821797176:android:8add1001f4ec55701445cd',
    messagingSenderId: '254821797176',
    projectId: 'allobaby-a14cd',
    storageBucket: 'allobaby-a14cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4mJh2-MPcFb2ov9bt9jSZhFGkoSQeyds',
    appId: '1:254821797176:ios:05059a2df587e3e71445cd',
    messagingSenderId: '254821797176',
    projectId: 'allobaby-a14cd',
    storageBucket: 'allobaby-a14cd.firebasestorage.app',
    iosBundleId: 'com.example.allobaay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4mJh2-MPcFb2ov9bt9jSZhFGkoSQeyds',
    appId: '1:254821797176:ios:05059a2df587e3e71445cd',
    messagingSenderId: '254821797176',
    projectId: 'allobaby-a14cd',
    storageBucket: 'allobaby-a14cd.firebasestorage.app',
    iosBundleId: 'com.example.allobaay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSz_YVVvHMCjLcQoL4UC8L7-gV3Ti8iXk',
    appId: '1:254821797176:web:b0af2948d51b75271445cd',
    messagingSenderId: '254821797176',
    projectId: 'allobaby-a14cd',
    authDomain: 'allobaby-a14cd.firebaseapp.com',
    storageBucket: 'allobaby-a14cd.firebasestorage.app',
    measurementId: 'G-80L9RZ3C0L',
  );
}
